version: '3'
services:
  backend:
    build: ./backend
    container_name: backend
  frontend:
    image: nginx:alpine
    container_name: frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
